# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SimbirNote' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SimbirNote

  pod 'SnapKit'      
  pod 'FSCalendar'   
  pod 'RealmSwift'

end
